(letrec ([test$1 (lambda ()
                  (locals (a.1 b.2 c.3 d.4 e.5 f.6 g.7 h.8 i.9 j.10 k.11 l.12 m.13 n.14)
                    (begin
                      (set! a.1 fv2)
                      (set! b.2 fv3)
                      (set! c.3 fv1)
                      (set! e.5 rax)
											(set! d.4 fv6)                      
                      (set! f.6 d.4)
                      (set! g.7 fv5)
                      (set! h.8 fv7)
                      (set! i.9 0)
                      (set! j.10 a.1)
                      (set! n.14 (* n.14 rax))
                      (set! k.11 (* k.11 rax))
                      (set! n.14 (+ n.14 k.11))
                      (set! g.7 (- g.7 a.1))
                      (set! n.14 (- n.14 g.7))
                      (set! k.11 (* k.11 e.5))
                      (set! n.14 k.11)
                      (set! l.12 (+ l.12 c.3))
                      (set! n.14 (* n.14 k.11))
                      (set! i.9 (* i.9 g.7))
                      (set! n.14 (+ n.14 i.9))
                      (set! m.13 d.4)
                      (set! n.14 (+ n.14 m.13))
                      (set! m.13 (+ m.13 fv6))
											(set! a.1 (+ a.1 fv2))
                      (set! n.14 (+ n.14 a.1))											
                      (set! i.9 (+ i.9 a.1))
                      (set! a.1 (+ a.1 m.13))
                      (set! j.10 (+ j.10 c.3))
                      (set! f.6 (* f.6 2))
                      (set! rax h.8)
                      (r15 rax))))])
  (locals ()
    (begin
      (set! fv0 18)
			(set! rax (+ rax fv0))
      (set! fv1 5)
      (set! fv2 9)
      (set! fv3 12)
      (set! fv4 91)
      (set! fv5 17)
      (set! fv6 52)
      (set! fv7 36)
      (test$1 rax rbp fv0 fv1 fv2 fv3 fv4 fv5 fv6 fv7))))

			(letrec ([if-test$1 (lambda ()
	                           (locals (x.5 y.2 z.3 a.1)
	                             (begin
																 (set! x.5 5)
																 (set! a.1 1)
																 (set! y.2 2)
																 (set! z.3 1)
	                               (if (= x.5 0)
	                                   (set! x.5 (+ x.5 12))
	                                   (set! x.5 (- x.5 10)))
	                               (set! x.5 (* x.5 10))
	                               (set! fv0 z.3)
																 (set! x.5 a.1)
	                               (r15 rax))))])
	       (locals () (if-test$1 r15)))
